package Exceptions;

//import java.util.Scanner;

class Exercise1 {
	/*public static void main(String[] args) {
		Scanner obj = new Scanner(System.in);
		System.out.println("ENTER THE VALUE OF 'a' : ");
		int a = obj.nextInt();
		System.out.println("ENTER THE VALUE OF 'b' : ");
		int b = obj.nextInt();
		try {
			int ans = a/b;
			System.out.println("ANSWER IS : "+ans);
		}
		catch(ArithmeticException e){
			System.out.println("Division by zero is not possible");
		}finally {
			System.out.println("THE OPERATION IS COMPLETED");
		}
	}*/
public static void main(String[] args) {
	int x = 10;
	double y = x;
	System.out.println(y);
	double a = 12.48;
	int b = (int)a;
	System.out.println(b);
}
}
